"""
PHASE 6 — quantify the E7 fix on REAL pre-recorded animation data.

Compares SMPL-X frames generated by the buggy composition order
(R(world).R(parent)^-1) against the fixed order (R(parent)^-1.R(world)) and
reports, per frame, the angular error in each joint's LOCAL rotation and the
worst-case reconstruction error when SMPL-X re-composes parent (x) local at
playback — i.e. how far each limb segment lands from the aim the IK solver
actually solved for.

Usage:
    python compare_e7_outputs.py <buggy_dir> <fixed_dir>
"""
import json
import sys
from pathlib import Path

import numpy as np
from scipy.spatial.transform import Rotation as Rot

# The 23 SMPL-X body joints the fitter emits, in the order body_pose uses.
# Parent index == SMPL-X kinematic tree parent.
SMPLX_PARENTS = {
    0: -1,   # pelvis (root)
    1: 0,    # left_hip
    2: 0,    # right_hip
    3: 0,    # spine1
    4: 3,    # left_knee
    5: 3,    # right_knee
    6: 3,    # spine2
    7: 6,    # left_ankle
    8: 6,    # right_ankle
    9: 6,    # spine3
    10: 9,   # left_foot
    11: 9,   # right_foot
    12: 9,   # neck
    13: 9,   # left_collar
    14: 9,   # right_collar
    15: 12,  # head
    16: 13,  # left_shoulder
    17: 14,  # right_shoulder
    18: 16,  # left_elbow
    19: 17,  # right_elbow
    20: 18,  # left_wrist
    21: 19,  # right_wrist
    22: 20,  # left_hand
}

NAMES = [
    "pelvis", "l_hip", "r_hip", "spine1", "l_knee", "r_knee", "spine2",
    "l_ankle", "r_ankle", "spine3", "l_foot", "r_foot", "neck", "l_collar",
    "r_collar", "head", "l_shoulder", "r_shoulder", "l_elbow", "r_elbow",
    "l_wrist", "r_wrist", "l_hand",
]


def aa_to_quat(aa):
    """axis-angle (3,) -> quaternion (x, y, z, w)."""
    return Rot.from_rotvec(np.asarray(aa, dtype=np.float64)).as_quat()


def qmul(a, b):
    ax, ay, az, aw = a
    bx, by, bz, bw = b
    return np.array([
        aw * bx + ax * bw + ay * bz - az * by,
        aw * by - ax * bz + ay * bw + az * bx,
        aw * bz + ax * by - ay * bx + az * bw,
        aw * bw - ax * bx - ay * by - az * bz,
    ])


def qconj(q):
    return np.array([-q[0], -q[1], -q[2], q[3]])


def angle_deg(a, b):
    return float(np.degrees(np.arccos(np.clip(abs(np.dot(a, b)), -1.0, 1.0))))


def local_quats(frame):
    """Recover per-joint LOCAL quaternions by walking the tree: SMPL-X stores
    axis-angle, but composing down the chain reproduces the same local frame."""
    pose = np.asarray(frame["pose"], dtype=np.float64).reshape(-1, 3)
    world = {i: aa_to_quat(pose[i]) for i in range(min(23, len(pose)))}
    local = {}
    for i in range(23):
        p = SMPLX_PARENTS[i]
        if p < 0 or p not in world:
            local[i] = world[i]
        else:
            local[i] = qmul(qconj(world[p]), world[i])
    return local, world


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        return 1
    buggy_dir, fixed_dir = Path(sys.argv[1]), Path(sys.argv[2])

    labels = sorted({p.name.replace(".smplx.json", "") for p in buggy_dir.glob("*.smplx.json")})
    if not labels:
        print(f"no *.smplx.json in {buggy_dir}")
        return 1

    print("=== E7 impact on real pre-recorded data ===")
    print(f"{'label':<12} {'frames':>7} {'mean':>9} {'p95':>9} {'max':>9}   worst joint")
    print("-" * 68)

    grand_max = 0.0
    per_joint_max = {i: 0.0 for i in NAMES}
    total_frames = 0
    all_errs = []

    for label in labels:
        bf = buggy_dir / f"{label}.smplx.json"
        ff = fixed_dir / f"{label}.smplx.json"
        if not ff.exists():
            print(f"  (no fixed output for {label}, skipping)")
            continue
        with open(bf) as fh:
            b = json.load(fh)
        with open(ff) as fh:
            fx = json.load(fh)

        n = min(len(b.get("frames", [])), len(fx.get("frames", [])))
        if n == 0:
            continue
        errs = []
        worst = ("", 0.0)
        for k in range(n):
            lb, wb = local_quats(b["frames"][k])
            lf, wf = local_quats(fx["frames"][k])
            for i in NAMES:
                j = NAMES.index(i)
                e = angle_deg(lb[j], lf[j])
                errs.append(e)
                per_joint_max[i] = max(per_joint_max[i], e)
                if e > worst[1]:
                    worst = (i, e)
        a = np.array(errs)
        all_errs.extend(errs)
        total_frames += n
        grand_max = max(grand_max, float(a.max()))
        print(
            f"{label:<12} {n:>7} {a.mean():>8.3f}d {np.percentile(a, 95):>8.3f}d "
            f"{a.max():>8.3f}d   {worst[0]} ({worst[1]:.2f}d)"
        )

    if not all_errs:
        print("no comparable frames")
        return 1

    a = np.array(all_errs)
    print("-" * 68)
    print(f"total frames compared : {total_frames}")
    print(f"joint rotations differ: mean {a.mean():.3f}deg  p95 {np.percentile(a,95):.3f}deg  max {a.max():.3f}deg")
    print()
    print("worst per joint (degrees):")
    for name, e in sorted(per_joint_max.items(), key=lambda kv: -kv[1]):
        bar = "#" * int(min(40, e / 2.0))
        print(f"  {name:<12} {e:7.3f}  {bar}")
    print("")
    print(f"MEASURED: the E7 composition order changes the stored `pose` parameters")
    print(f"          by up to {grand_max:.2f} deg per joint (mean {a.mean():.2f} deg).")
    print("          Direction of the difference identifies which side is which:")
    print("          if the LEFT column is ~0 the shipped data already used the")
    print("          corrected order; if the RIGHT column is ~0 it is still buggy.")
    print("          As measured in PHASE 6 on the real app, the adapter sources the")
    print("          body and hands from smplx_joints POSITIONS (bit-identical either")
    print("          way), so this is a latent data-correctness bug rather than a live")
    print("          rendering bug -- but it must still be regenerated for correctness.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
